### ISSUE TITLE
babel-plugin-react-compiler  devDep

### ISSUE THREAD

**Issue by Ayc0** [SukkaW/react-compiler-webpack#6]
Hello 👋 

As you're directly importing `babel-plugin-react-compiler` in your code, shouldn't it be a dependency instead of a devDependency?

Otherwise it won't be installed in people's installs, and not even importable when used with package managers like pnpm or yarn pnp

**Comment by SukkaW** [comment]
It is actually a **peer dependency**. So you can always install your desired version of `babel-plugin-react-compiler` (not bound with `react-compiler-webpack`), and if you don't explicitly install one in your project, most package managers will automatically install peer depdencies for you.

**Comment by Ayc0** [comment]
I misread the package.json, sorry for the inconvenience

Thanks!
